# Generated by Django 4.1 on 2022-12-14 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Body',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('height', models.CharField(blank=True, max_length=20, null=True)),
                ('weight', models.CharField(blank=True, max_length=20, null=True)),
                ('eye_l', models.CharField(blank=True, db_column='eye_L', max_length=20, null=True)),
                ('eye_r', models.CharField(blank=True, db_column='eye_R', max_length=20, null=True)),
                ('disease', models.CharField(blank=True, max_length=30, null=True)),
            ],
            options={
                'db_table': 'body',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Employees',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=20, null=True)),
                ('birth', models.CharField(blank=True, max_length=10, null=True)),
                ('gender', models.IntegerField()),
                ('depart', models.CharField(blank=True, max_length=20, null=True)),
                ('class_field', models.CharField(blank=True, db_column='class', max_length=20, null=True)),
                ('phone', models.CharField(blank=True, max_length=20, null=True)),
                ('addr', models.CharField(blank=True, max_length=30, null=True)),
                ('email', models.CharField(blank=True, max_length=20, null=True)),
                ('resi_num', models.CharField(blank=True, max_length=20, null=True)),
                ('hire_date', models.CharField(blank=True, max_length=20, null=True)),
                ('image', models.CharField(blank=True, max_length=200, null=True)),
            ],
            options={
                'db_table': 'employees',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Info',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('salary', models.CharField(blank=True, max_length=20, null=True)),
                ('task', models.CharField(blank=True, max_length=200, null=True)),
                ('graduation', models.CharField(blank=True, max_length=200, null=True)),
                ('license', models.CharField(blank=True, max_length=200, null=True)),
            ],
            options={
                'db_table': 'info',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Soldier',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(blank=True, max_length=20, null=True)),
                ('s_rank', models.CharField(blank=True, max_length=20, null=True)),
                ('number', models.CharField(blank=True, max_length=20, null=True)),
                ('state', models.CharField(blank=True, max_length=20, null=True)),
                ('depart', models.CharField(blank=True, max_length=20, null=True)),
                ('on_date', models.CharField(blank=True, max_length=20, null=True)),
                ('out_date', models.CharField(blank=True, max_length=20, null=True)),
                ('discharge', models.CharField(blank=True, max_length=20, null=True)),
            ],
            options={
                'db_table': 'soldier',
                'managed': False,
            },
        ),
    ]
